# -*- coding: utf-8 -*-
"""歡迎使用 Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install taiwanlottery

from TaiwanLottery import TaiwanLotteryCrawler
lottery = TaiwanLotteryCrawler()
result = lottery.daily_cash(['2020', '02'])

year = ['2020', '2021', '2022', '2023', '2024', '2025']

month = ['01','02','03','04','05','06','07','08','09','10','11','12']

all_result = []
for y in year:
  for m in month:
    for r in lottery.daily_cash([y, m]):
      all_result.append(r['獎號'])

len(all_result)

count_list = []
for r in all_result:
  count = 0
  for comp in all_result:
    equal_count = 0
    for num in r:
      if num in comp:
        equal_count += 1
    if equal_count == 3:
      count += 1
  count_list.append(count)

sum(count_list)/len(count_list)

answer=[]

def compare_count(answer):
  count = 0
  for comp in all_result:
      equal_count = 0
      for num in answer:
        if num in comp:
          equal_count += 1
      if equal_count >= 4:
        count += 1
  print(count)

num_count_list = [0]*39
for i in range(1,40):
  for r in all_result[1553:1653]:
    if i in r:
      num_count_list[i-1] += 1

summation = sum(num_count_list)
num_count_list = [num/summation for num in num_count_list]

sum(num_count_list)

import numpy as np

np.random.choice(a=range(1,40), size=5, replace=False, p=num_count_list)

compare_count([ 7, 15,  8,  9, 13])

compare_count([32,  3, 12, 31,  9])

